manifest:
  defaults:
    remote: zephyrproject
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: libcoap-official
      url-base: https://github.com/obgm
  projects:
    - name: zephyr
      remote: zephyrproject
      repo-path: zephyr
      revision: v4.3.0
      path: zephyr
      import:
        name-allowlist:
          - hal_espressif  # ESP32 HAL
          - mbedtls        # TLS/crypto library
          - picolibc       # C library
    - name: libcoap
      remote: libcoap-official
      repo-path: libcoap
      revision: 0bf6a2d7  # v4.3.5-187 - pinned for reproducible builds
      path: modules/lib/libcoap
  self:
    path: .